FROM balenalib/%%BALENA_ARCH%%-debian-python:3-stretch
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
  dbus \
  avahi-daemon \
  avahi-discover \
  avahi-utils \
  libnss-mdns \
  mdns-scan \
  systemd
RUN pip3 install aioesphomeapi blynklib
COPY start-thermostat.sh /srv/thermostat/start-thermostat.sh
COPY thermostat/* /srv/thermostat/thermostat/
RUN chmod 0755 /srv/thermostat/start-thermostat.sh
CMD /srv/thermostat/start-thermostat.sh
